---
title: "Machine Learning Project"
author: "Yuchen Zhang"
date: "6/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(stringr)
```

```{r}
url <- "https://arxiv.org/"
arXiv <- read_html(url)
arXiv_session <- html_session(url)

get_link <- function(link, tag) {
  read_html(link) %>% 
    html_nodes(tag) %>%
    html_attr("href") %>% 
    paste(url, ., sep = "")
}

logic_link <- get_link(url, 
                       "#math\\.LO")

apaper_link <- get_link(logic_link, 
                        "dl:nth-child(9) .list-identifier a:nth-child(1)")

otherformat_link <- get_link(apaper_link, 
                             ".full-text li~ li+ li .abs-button")

download_link <- get_link(otherformat_link, 
                          "dd b+ a")

# useless for now
arXiv_session %>% 
  jump_to(logic_link) %>% 
  jump_to(apaper_link) %>% 
  jump_to(otherformat_link)


# https://arxiv.org/e-print/2006.14048

download.file(download_link, "./Download/targz/a.tar.gz")

# some problems here
# untar.gz files
untar("./Download/targz/a.tar.gz", 
      exdir = "./Download/unzipped",
      list = TRUE)



```

